### PR TITLE
BCB-1566 misc minor improvements.  Some print statements. Warning

### PR DESCRIPTION
**Pull request by jeffalleyusgs**
when no dam geometry exists for a dam.  Added tls-ca-bundle.pem file and updated the README for this file.

### CODE REVIEW

**Comment by dwief-usgs** [comment]
@jeffalleyusgs 
Thanks for the work on this.  Sorry it took a few days and apologize I'm not just resolving on my end.

1) Can you reformat print statements to be consistent with other print statements in the package.  
eg. from drip_dam module ->  f"Unknown Source for id: {dam_id}. "

2) I understand reasoning for adding PEM but question if that is appropriate... that is an internal issue and not sure we should be exposing that issue in a public repo   @aulenbac  any thoughts on that?

3) Not sure I know the answer but is it necessary to add the True False returns or can we just use the object

**Comment by jeffalleyusgs** [comment]
@dwief-usgs , Thanks for the comments!
I can certainly address issue 1
As for issue 2, I didn't realize this was a public repo.  I know that security/permission issues kept me from running the pipeline locally until I installed the PEM file.  That file needs to be stored somewhere, but if this project isn't the appropriate place, I'm happy to move it.  Again, @aulenbac will need to weigh-in here.
Issue 3: I'll look into this.  I had never written a line of python until a few weeks ago so my python code may not be the most efficient.  I'm still learning a great deal on a daily basis.  I always strive for readability above all else, but it is important that I do things the "python way".  I'll change this if using the object directly will achieve the same results.

**Comment by dwief-usgs** [comment]
@jeffalleyusgs   

I'd rather PEM not be included in the repo.  

Issue 3 ->  check to see if hasattr does what you need...... https://stackoverflow.com/questions/610883/how-to-know-if-an-object-has-an-attribute-in-python

**Comment by aulenbac** [comment]
The pem should not be in there. I agree with @dwief-usgs, @jeffalleyusgs

**Comment by jeffalleyusgs** [comment]
Okay, I’ll remove it.
J

Jeff Alley
Astor & Sanders Employee (A&S)
Software Architect/Developer
ANJV / BCB
jalley@contractor.usgs.gov<mailto:jalley@contractor.usgs.gov>
Mobile: 307.920.2225

**Comment by jeffalleyusgs** [comment]
I will update the pull request later today and get that removed.

Jeff

Jeff Alley
Astor & Sanders Employee (A&S)
Software Architect/Developer
ANJV / BCB
jalley@contractor.usgs.gov<mailto:jalley@contractor.usgs.gov>
Mobile: 307.920.2225

**Comment by dwief-usgs** [comment]
@jeffalleyusgs  I removed the print for successful geometries.  I didn't see added value for that print... If I was missing something let me know.  I updated that and will accept PR, thanks

**Comment by jeffalleyusgs** [comment]
@dwief-usgs , I'm still new to what all the drip pipeline does and missed that it's generating a .csv file.   You are correct.  That file is a fine representation of what's happening.  I can use it when trouble-shooting.  I just put the print in there for a visual feedback while running at the console.  Any time I'm running a process that doesn't complete instantly, I like some visual feedback that it's actually processing and not stuck--sort of like the busy indicators when you submit something to a web site or whatever.  I'm cool without it.  It's just a style thing.  I tend to be a bit free-er with prints and instrumentation of purely backend processes since customers don't see them.   Which brings up the question: The drip pipeline execution is definitely just a backend process, right?   The API is where the customer interacts.    This is all part of getting to know how to operate on a new team.  I'm cool!   Thanks for your patience. J

**Pull request merged**
